[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
error = { path = "../error" }
lexer = { path = "../lexer" }
parser = { path = "../parser" }
evaluator = { path = "../evaluator" }
